source 'https://github.com/LivePersonInc/iOSPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

target 'SampleApp' do  
   pod 'Auth0', '~> 1.32'
   pod 'LPMessagingSDK'
end
