# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'
use_frameworks!
source 'https://github.com/LivePersonInc/iOSPodSpecs.git' #LiveEngage Pod Repository

target 'SampleApp' do

  # Pods for SampleApp
  #LPMessagingSDK Includes: LPAMS.framework, LPInfra.framework, LPMessagingSDK.framework and  LPMessagingSDKModels.bundle
  pod 'LPMessagingSDK'
end
